# Generated by Django 5.2.5 on 2025-08-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글내용')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltest.post', verbose_name='선택할 포스트')),
            ],
        ),
    ]
